version: '3.7'

services:
  backend:
    image:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod
