version: "3.7"

services:
  backend:
    # image: asia.gcr.io/backend-371412/rungether-nestjs:4.2  //meonjifather.shop
    # image: asia.gcr.io/rungether-374202/rungether-nestjs:0.0.1
    image: asia.gcr.io/backend-371412/rungether-nestjs:5.1
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
